version: "3.7"
services:
  survey:
    build:
      args:
        user: www
        uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    image: laravel-image
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - ./.env
    networks:
      - app-network
  db:
    image: mariadb:latest
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    env_file:
      - ./.env
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
